### ISSUE TITLE
WebHook Signature error

### ISSUE THREAD

**Issue by liuzeng01** [xusenlin/ForestBlog#2]
请问能把添加WebHook步骤写的再详细些吗？出了些问题，配置完webhook密钥后显示不匹配

**Comment by xusenlin** [comment]
你好，你可以尝试以下步骤。
1. 启动应用之前先配置好 config.json 的 webHookSecret 字段。
2. 在 github 的仓库添加 webhook ，具体路径为
Settings->WebHooks->Add webhook(填写地址：http://你的域名.com/api/git_push_hook 和 Secret )

目前还不支持其他仓库，因为诸如 gitlab 的仓库 webhook 携带的 Secret 被定义在了其他字段。如果不需要验证 Secret 可以在 
 controller/webhook.go 文件的 GithubHook 方法中只保留 ```models.CompiledContent()```这一行代码。
